#pragma once

#define GPU_MAX_USHADERS 16

enum {
	HASHA_HOST_RESET,
	HASHA_HOST_TO_USHADER_MST,
	HASHA_HOST_TO_VIDEOCTRL_MST,
	HASHA_HOST_FROM_USHADER_SLV,
	HASHA_HOST_TO_BUSMUX_MST,
	HASHA_HOST_TO_USHADER_HALT_REQ,
	HASHA_HOST_TO_BUSMUX,
	
	HOST_MAX_HASHA_PORTS
};
enum {
	HASHA_USHADER_RESET,
	HASHA_USHADER_FROM_PREV,
	HASHA_USHADER_TO_PREV,
	HASHA_USHADER_FROM_NEXT,
	HASHA_USHADER_TO_NEXT,
	HASHA_USHADER_HALT_REQ,
	
	USHADER_MAX_HASHA_PORTS
};

enum {
	HASHA_VIDEOCTRL_RESET,
	HASHA_VIDEOCTRL_SLV,
	HASHA_VIDEOCTRL_HALT_REQ,
	
	VIDEOCTRL_MAX_HASHA_PORTS
};

//~ const size_t HOST_MAX_HASHA_PORTS = HASHA_HOST_PORTS_NUM;
//~ const size_t USHADER_MAX_HASHA_PORTS = 4;
//~ const size_t VIDEOCTRL_MAX_HASHA_PORTS = 1;

const size_t DUMMY_ID = 0;
