#define GPU_MAX_USHADERS 4

enum {
	HASHA_HOST_TO_USHADER_MST = 0,
	HASHA_HOST_TO_VIDEOCTRL_MST
};
enum {
	HASHA_HOST_TO_USHADER_SLV,
};
enum {
	HASHA_USHADER_UPSTREAM_MST = 0,
	HASHA_USHADER_DOWNSTREAM_MST
};
enum {
	HASHA_USHADER_UPSTREAM_SLV = 0,
	HASHA_USHADER_DOWNSTREAM_SLV
};

enum {
	HASHA_VIDEOCTRL_SLV = 0
};

const size_t HOST_MAX_HASHA_MST_LANES = 2;
const size_t HOST_MAX_HASHA_SLV_LANES = 1;

const size_t USHADER_MAX_HASHA_MST_LANES = 2;
const size_t USHADER_MAX_HASHA_SLV_LANES = 2;

const size_t VIDEOCTRL_MAX_HASHA_MST_LANES = 0;
const size_t VIDEOCTRL_MAX_HASHA_SLV_LANES = 1;

const size_t DUMMY_ID = 0;
